#!/bin/sh

commit_message=$(<"$1")

if ! [[ $commit_message =~ ^(vingo:|vinscant:|vinvoor:|zess:) ]]; then
    echo "Error: commit message should start with vingo:|vinscant:|vinvoor:|zess: depending on which subproject you are working on."
    exit 1
fi

if ! [[ $commit_message =~ ^.*:\ [a-z].* ]]; then
    echo "Error: first letter after project specifier should be lower case
Example:
    vingo: add cheese
           ^
           | this one"
    exit 1
fi

exit 0