#!/usr/bin/env bash
# some (*)nix distros dont have /bin/bash

cd vinvoor/

yarn run format

if [ $? -ne 0 ]; then
    echo "Error: code improperly formatted!"
    exit 1
fi

yarn run lint

if [ $? -ne 0 ]; then
    echo "Error: code improperly linted!"
    exit 1
fi

exit 0
