services:
    zess-db:
        image: postgres:alpine3.20
        environment:
            - POSTGRES_PASSWORD=zess
            - POSTGRES_USER=zess
            - POSTGRES_DB=zess
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        extra_hosts:
            - "host.docker.internal:host-gateway"

    zess-backend:
        env_file: "vingo/.env"
        environment:
            - CARGO_BUILD_TARGET_DIR=/target
        build:
            context: vingo
            dockerfile: Dockerfile.dev
        ports:
            - 4000:4000
        volumes:
            - ./vingo:/backend
            - backend-target:/target
        extra_hosts:
            - "host.docker.internal:host-gateway"
        stop_grace_period: 1s
        depends_on:
            - zess-db

    zess-frontend:
        build:
            context: vinvoor
            dockerfile: Dockerfile.dev
        user: ${CURRENT_UID}
        ports:
            - 5173:5173
        volumes:
            - ./vinvoor:/frontend
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    backend-target:
    db-data:
