//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::card::Entity as Card;
pub use super::day::Entity as Day;
pub use super::scan::Entity as Scan;
pub use super::season::Entity as Season;
pub use super::user::Entity as User;
