CREATE TABLE IF NOT EXISTS days (
			id SERIAL NOT NULL PRIMARY KEY,
			date DATE NOT NULL UNIQUE
		);

CREATE TABLE IF NOT EXISTS users (
			id INTEGER PRIMARY KEY,
			username TEXT NOT NULL,
			admin BOOLEAN DEFAULT FALSE NOT NULL,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
		);

CREATE TABLE IF NOT EXISTS settings (
			user_id INT NOT NULL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
			public BOOLEAN NOT NULL DEFAULT FALSE,
			scan_in_out BOOLEAN NOT NULL DEFAULT FALSE,
			leaderboard BOOLEAN NOT NULL DEFAULT TRUE
		);

CREATE TABLE IF NOT EXISTS cards (
			serial TEXT NOT NULL PRIMARY KEY UNIQUE,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
			user_id INTEGER NOT NULL REFERENCES users(id)
		);

CREATE TABLE IF NOT EXISTS scans (
			id SERIAL NOT NULL PRIMARY KEY,
			scan_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
			scan_in BOOLEAN,
			card_serial TEXT NOT NULL REFERENCES cards(serial)
		);