---
name: Vingo Audit Rust dependencies
on:
  pull_request:
    paths:
      - .github/workflows/vingo_audit.yml
      - 'vingo/**/Cargo.toml'
      - 'vingo/**/Cargo.lock'

  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  security_audit:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      checks: write

    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: vingo/
