name: "vingo: check style"

on: 
  push:
    paths:
      - ".github/workflows/vingo.yml"
      - "vingo/**"
  pull_request:
    paths:
      - ".github/workflows/vingo.yml"
      - "vingo/**"
  workflow_dispatch:

jobs:
  formatting:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"

    - uses: "actions-rs/toolchain@v1.0.6"
      with:
        toolchain: "stable"
        components: "rustfmt"
        override: true

    - name: "cargo fmt"
      working-directory: "vingo/"
      run: "cargo fmt -- --check"

  clipy:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"

    - uses: "actions-rs/toolchain@v1.0.6"
      with:
        toolchain: "stable"
        components: "clippy"
        override: true

    - name: "cargo clippy"
      working-directory: "vingo/"
      run: "cargo clippy --locked --all-targets --all-features"
