name: Format and linting

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/vinvoor_format_lint.yml
      - 'vinvoor/**'
  pull_request:
    paths:
      - .github/workflows/vinvoor_format_lint.yml
      - 'vinvoor/**'

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.15.1

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: vinvoor/

      - name: Run formatter
        run: pnpm prettier --check .
        working-directory: vinvoor/

      - name: Run Linter
        run: pnpm eslint . --max-warnings=0
        working-directory: vinvoor/
