name: "vinvoor: format, lint and typecheck"

on:
  push:
    paths:
      - ".github/workflows/vinvoor.yml"
      - "vinvoor/**"
  pull_request:
    paths:
      - ".github/workflows/vinvoor.yml"
      - "vinvoor/**"
  workflow_dispatch:

jobs:
  format-lint-typecheck:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-node@v3"
        with:
          node-version: "24.8.0"
      - run: "npm install -g pnpm"

      - run: "pnpm install"
        working-directory: "vinvoor/"

      - name: "format and lint"
        working-directory: "vinvoor/"
        run: "pnpm eslint ."

      - name: "typecheck"
        working-directory: "vinvoor/"
        run: "pnpm tsc --noEmit"
