name: Vinvoor Format, Lint & Typecheck

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.8.0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: vinvoor/

      - name: Run format & lint
        run: pnpm eslint .
        working-directory: vinvoor/

      - name: Run typecheck
        run: pnpm tsc --noEmit
        working-directory: vinvoor/
